plugins {
id 'com.android.application'
}

android {
namespace "com.example.dpc"
compileSdk 34

lint {
checkReleaseBuilds false
}

defaultConfig {  
    applicationId "com.example.dpc"  
    minSdk 29
    targetSdk 37
    versionCode 10
    versionName "10.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
    }  
}

}

dependencies {
}
